In [1]:
import numpy as np
matrixA = np.arange(24).reshape(2,3,4)
print(matrixA)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [3]:
import cv2
img = cv2.imread("./input/ransacTest_image.png")
print(img.shape)

(480, 640, 3)


In [2]:
print(matrixA[..., 1])
print("shape:",matrixA[...,1].shape)
#输出结果matrixA
"""
[[ 1  5  9]
 [13 17 21]]
matrixA shape: (2, 3)
"""
matrixB = np.arange(24).reshape(2,3,4)
print(matrixB[:,:,1])
print(matrixB[:,:,1].shape)
#输出结果matrixB
"""
[[ 1  5  9]
 [13 17 21]]
matrixB shape: (2, 3)
"""

[[ 1  5  9]
 [13 17 21]]
shape: (2, 3)
[[ 1  5  9]
 [13 17 21]]
(2, 3)


'\n[[ 1  5  9]\n [13 17 21]]\nmatrixB shape: (2, 3)\n'